import {
  MantineReactTable,
  type MRT_RowData,
  type MRT_TableOptions,
  useMantineReactTable,
} from 'mantine-react-table';
import style from './style.module.css';

const MRT_Localization_ES = {
  actions: 'Acciones',
  and: 'y',
  cancel: 'Cancelar',
  changeFilterMode: 'Cambiar modo de filtro',
  changeSearchMode: 'Cambiar modo de búsqueda',
  clearFilter: 'Limpiar filtro',
  clearSearch: 'Limpiar búsqueda',
  clearSort: 'Limpiar ordenamiento',
  clickToCopy: 'Click para copiar',
  collapse: 'Colapsar',
  collapseAll: 'Colapsar todo',
  columnActions: 'Acciones de columna',
  copiedToClipboard: 'Copiado al portapapeles',
  dropToGroupBy: 'Soltar para agrupar por {column}',
  edit: 'Editar',
  expand: 'Expandir',
  expandAll: 'Expandir todo',
  filterArrIncludes: 'Incluye',
  filterArrIncludesAll: 'Incluye todos',
  filterArrIncludesSome: 'Incluye algunos',
  filterBetween: 'Entre',
  filterBetweenInclusive: 'Entre (inclusive)',
  filterByColumn: 'Filtrar por {column}',
  filterContains: 'Contiene',
  filterEmpty: 'Vacío',
  filterEndsWith: 'Termina con',
  filterEquals: 'Igual a',
  filterEqualsDate: 'Igual a',
  filterEqualsNumber: 'Igual a',
  filterFuzzy: 'Búsqueda difusa',
  filterGreaterThan: 'Mayor que',
  filterGreaterThanOrEqualTo: 'Mayor o igual que',
  filterInNumberRange: 'Entre',
  filterIncludesString: 'Contiene',
  filterIncludesStringSensitive: 'Contiene',
  filterLessThan: 'Menor que',
  filterLessThanOrEqualTo: 'Menor o igual que',
  filterMode: 'Modo de filtro: {filterType}',
  filterNotEmpty: 'No vacío',
  filterNotEquals: 'No igual a',
  filterStartsWith: 'Empieza con',
  filterWeakEquals: 'Igual a',
  filteringByColumn: 'Filtrando por {column} - {filterType} - {filterValue}',
  goToFirstPage: 'Ir a la primera página',
  goToLastPage: 'Ir a la última página',
  goToNextPage: 'Ir a la página siguiente',
  goToPreviousPage: 'Ir a la página anterior',
  grab: 'Agarrar',
  groupByColumn: 'Agrupar por {column}',
  groupedBy: 'Agrupado por ',
  hideAll: 'Ocultar todo',
  hideColumn: 'Ocultar columna {column}',
  max: 'Máximo',
  min: 'Mínimo',
  move: 'Mover',
  noRecordsToDisplay: 'No hay registros para mostrar',
  noResultsFound: 'No se encontraron resultados',
  of: 'de',
  or: 'o',
  pinToLeft: 'Anclar a la izquierda',
  pinToRight: 'Anclar a la derecha',
  resetColumnSize: 'Restablecer tamaño de columna',
  resetOrder: 'Restablecer orden',
  rowActions: 'Acciones de fila',
  rowNumber: '#',
  rowNumbers: 'Números de fila',
  rowsPerPage: 'Filas por página',
  save: 'Guardar',
  search: 'Buscar',
  select: 'Seleccionar',
  selectedCountOfRowCountRowsSelected: '{selectedCount} de {rowCount} fila(s) seleccionada(s)',
  showAll: 'Mostrar todo',
  showAllColumns: 'Mostrar todas las columnas',
  showHideColumns: 'Mostrar/Ocultar columnas',
  showHideFilters: 'Mostrar/Ocultar filtros',
  showHideSearch: 'Mostrar/Ocultar búsqueda',
  sortByColumnAsc: 'Ordenar por {column} ascendente',
  sortByColumnDesc: 'Ordenar por {column} descendente',
  sortedByColumnAsc: 'Ordenado por {column} ascendente',
  sortedByColumnDesc: 'Ordenado por {column} descendente',
  thenBy: ', luego por ',
  toggleDensity: 'Alternar densidad',
  toggleFullScreen: 'Alternar pantalla completa',
  toggleSelectAll: 'Alternar seleccionar todo',
  toggleSelectRow: 'Alternar seleccionar fila',
  toggleVisibility: 'Alternar visibilidad',
  ungroupByColumn: 'Desagrupar por {column}',
  unpin: 'Desanclar',
  unpinAll: 'Desanclar todo',
  unsorted: 'Sin ordenar',
};

export function CustomTable<TData extends MRT_RowData>(props: MRT_TableOptions<TData>) {
  const table = useMantineReactTable({
    localization: MRT_Localization_ES,
    manualFiltering: true,
    manualSorting: true,
    manualPagination: true,
    enableStickyHeader: true,
    enableStickyFooter: true,
    mantineTableProps: { striped: 'even' },
    mantinePaperProps: { className: style.paper },
    mantineTableContainerProps: {
      style: { maxHeight: 'calc(100vh - 250px)' },
    },
    positionActionsColumn: 'last',
    mantineTableHeadCellProps: ({ column }) => ({
      style: {
        ...(column.id === 'mrt-row-actions' && {
          width: '150px',
          minWidth: '150px',
          maxWidth: '200px',
        }),
      },
    }),
    mantineTableBodyCellProps: ({ column }) => ({
      style: {
        ...(column.id === 'mrt-row-actions' && {
          width: '150px',
          minWidth: '150px',
          maxWidth: '200px',
          textAlign: 'center',
        }),
      },
    }),

    ...props,
  });

  return <MantineReactTable table={table} />;
}
