export const QUERY_KEYS = Object.freeze({
  ADMINS: 'ADMINS',
  LOCALITIES: 'LOCALITIES',
  COMPANIES: 'COMPANIES',
  LEGAL_ENTITIES: 'LEGAL_ENTITIES',
  WORK_SHIFTS: 'WORK_SHIFTS',
  WORKERS: 'WORKERS',
  WORKER_ASSIGNMENTS: 'WORKER_ASSIGNMENTS',
});
