/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateRouteImport } from './pages/_private'
import { Route as PrivateWorkerAssignmentsRouteRouteImport } from './pages/_private/WorkerAssignments/route'
import { Route as PublicLoginIndexRouteImport } from './pages/_public/Login/index'
import { Route as PrivateAdministrationLocalitiesRouteRouteImport } from './pages/_private/Administration/Localities/route'
import { Route as PrivateAdministrationCompaniesRouteRouteImport } from './pages/_private/Administration/Companies/route'
import { Route as PrivateAdministrationAdminsRouteRouteImport } from './pages/_private/Administration/Admins/route'
import { Route as PrivateWorkerManagementWorkersIndexRouteImport } from './pages/_private/WorkerManagement/Workers/index'
import { Route as PrivateWorkerManagementWorkShiftIndexRouteImport } from './pages/_private/WorkerManagement/WorkShift/index'
import { Route as PrivateWorkerManagementBaseValuesIndexRouteImport } from './pages/_private/WorkerManagement/BaseValues/index'
import { Route as PrivateWorkerManagementWorkersListRouteRouteImport } from './pages/_private/WorkerManagement/Workers/List.route'
import { Route as PrivateWorkerManagementWorkShiftListRouteRouteImport } from './pages/_private/WorkerManagement/WorkShift/List.route'
import { Route as PrivateWorkerManagementBaseValuesListRouteRouteImport } from './pages/_private/WorkerManagement/BaseValues/List.route'

const PrivateDashboardIndexLazyRouteImport = createFileRoute(
  '/_private/Dashboard/',
)()
const PrivateAdministrationTerminalsRouteLazyRouteImport = createFileRoute(
  '/_private/Administration/Terminals',
)()
const PrivateAdministrationProductsRouteLazyRouteImport = createFileRoute(
  '/_private/Administration/Products',
)()
const PrivateAdministrationAgenciesRouteLazyRouteImport = createFileRoute(
  '/_private/Administration/Agencies',
)()

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/_private.lazy').then((d) => d.Route))
const PrivateWorkerAssignmentsRouteRoute =
  PrivateWorkerAssignmentsRouteRouteImport.update({
    id: '/WorkerAssignments',
    path: '/WorkerAssignments',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/WorkerAssignments/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateDashboardIndexLazyRoute =
  PrivateDashboardIndexLazyRouteImport.update({
    id: '/Dashboard/',
    path: '/Dashboard/',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Dashboard/index.lazy').then((d) => d.Route),
  )
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/Login/',
  path: '/Login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdministrationTerminalsRouteLazyRoute =
  PrivateAdministrationTerminalsRouteLazyRouteImport.update({
    id: '/Administration/Terminals',
    path: '/Administration/Terminals',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Terminals/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationProductsRouteLazyRoute =
  PrivateAdministrationProductsRouteLazyRouteImport.update({
    id: '/Administration/Products',
    path: '/Administration/Products',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Products/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationAgenciesRouteLazyRoute =
  PrivateAdministrationAgenciesRouteLazyRouteImport.update({
    id: '/Administration/Agencies',
    path: '/Administration/Agencies',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Agencies/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationLocalitiesRouteRoute =
  PrivateAdministrationLocalitiesRouteRouteImport.update({
    id: '/Administration/Localities',
    path: '/Administration/Localities',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Localities/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationCompaniesRouteRoute =
  PrivateAdministrationCompaniesRouteRouteImport.update({
    id: '/Administration/Companies',
    path: '/Administration/Companies',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Companies/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationAdminsRouteRoute =
  PrivateAdministrationAdminsRouteRouteImport.update({
    id: '/Administration/Admins',
    path: '/Administration/Admins',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Admins/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateWorkerManagementWorkersIndexRoute =
  PrivateWorkerManagementWorkersIndexRouteImport.update({
    id: '/WorkerManagement/Workers/',
    path: '/WorkerManagement/Workers/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateWorkerManagementWorkShiftIndexRoute =
  PrivateWorkerManagementWorkShiftIndexRouteImport.update({
    id: '/WorkerManagement/WorkShift/',
    path: '/WorkerManagement/WorkShift/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateWorkerManagementBaseValuesIndexRoute =
  PrivateWorkerManagementBaseValuesIndexRouteImport.update({
    id: '/WorkerManagement/BaseValues/',
    path: '/WorkerManagement/BaseValues/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateWorkerManagementWorkersListRouteRoute =
  PrivateWorkerManagementWorkersListRouteRouteImport.update({
    id: '/WorkerManagement/Workers/List',
    path: '/WorkerManagement/Workers/List',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/WorkerManagement/Workers/List.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateWorkerManagementWorkShiftListRouteRoute =
  PrivateWorkerManagementWorkShiftListRouteRouteImport.update({
    id: '/WorkerManagement/WorkShift/List',
    path: '/WorkerManagement/WorkShift/List',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/WorkerManagement/WorkShift/List.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateWorkerManagementBaseValuesListRouteRoute =
  PrivateWorkerManagementBaseValuesListRouteRouteImport.update({
    id: '/WorkerManagement/BaseValues/List',
    path: '/WorkerManagement/BaseValues/List',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/WorkerManagement/BaseValues/List.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/WorkerAssignments': typeof PrivateWorkerAssignmentsRouteRoute
  '/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/Administration/Agencies': typeof PrivateAdministrationAgenciesRouteLazyRoute
  '/Administration/Products': typeof PrivateAdministrationProductsRouteLazyRoute
  '/Administration/Terminals': typeof PrivateAdministrationTerminalsRouteLazyRoute
  '/Login': typeof PublicLoginIndexRoute
  '/Dashboard': typeof PrivateDashboardIndexLazyRoute
  '/WorkerManagement/BaseValues/List': typeof PrivateWorkerManagementBaseValuesListRouteRoute
  '/WorkerManagement/WorkShift/List': typeof PrivateWorkerManagementWorkShiftListRouteRoute
  '/WorkerManagement/Workers/List': typeof PrivateWorkerManagementWorkersListRouteRoute
  '/WorkerManagement/BaseValues': typeof PrivateWorkerManagementBaseValuesIndexRoute
  '/WorkerManagement/WorkShift': typeof PrivateWorkerManagementWorkShiftIndexRoute
  '/WorkerManagement/Workers': typeof PrivateWorkerManagementWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/WorkerAssignments': typeof PrivateWorkerAssignmentsRouteRoute
  '/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/Administration/Agencies': typeof PrivateAdministrationAgenciesRouteLazyRoute
  '/Administration/Products': typeof PrivateAdministrationProductsRouteLazyRoute
  '/Administration/Terminals': typeof PrivateAdministrationTerminalsRouteLazyRoute
  '/Login': typeof PublicLoginIndexRoute
  '/Dashboard': typeof PrivateDashboardIndexLazyRoute
  '/WorkerManagement/BaseValues/List': typeof PrivateWorkerManagementBaseValuesListRouteRoute
  '/WorkerManagement/WorkShift/List': typeof PrivateWorkerManagementWorkShiftListRouteRoute
  '/WorkerManagement/Workers/List': typeof PrivateWorkerManagementWorkersListRouteRoute
  '/WorkerManagement/BaseValues': typeof PrivateWorkerManagementBaseValuesIndexRoute
  '/WorkerManagement/WorkShift': typeof PrivateWorkerManagementWorkShiftIndexRoute
  '/WorkerManagement/Workers': typeof PrivateWorkerManagementWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_private/WorkerAssignments': typeof PrivateWorkerAssignmentsRouteRoute
  '/_private/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/_private/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/_private/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/_private/Administration/Agencies': typeof PrivateAdministrationAgenciesRouteLazyRoute
  '/_private/Administration/Products': typeof PrivateAdministrationProductsRouteLazyRoute
  '/_private/Administration/Terminals': typeof PrivateAdministrationTerminalsRouteLazyRoute
  '/_public/Login/': typeof PublicLoginIndexRoute
  '/_private/Dashboard/': typeof PrivateDashboardIndexLazyRoute
  '/_private/WorkerManagement/BaseValues/List': typeof PrivateWorkerManagementBaseValuesListRouteRoute
  '/_private/WorkerManagement/WorkShift/List': typeof PrivateWorkerManagementWorkShiftListRouteRoute
  '/_private/WorkerManagement/Workers/List': typeof PrivateWorkerManagementWorkersListRouteRoute
  '/_private/WorkerManagement/BaseValues/': typeof PrivateWorkerManagementBaseValuesIndexRoute
  '/_private/WorkerManagement/WorkShift/': typeof PrivateWorkerManagementWorkShiftIndexRoute
  '/_private/WorkerManagement/Workers/': typeof PrivateWorkerManagementWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/WorkerAssignments'
    | '/Administration/Admins'
    | '/Administration/Companies'
    | '/Administration/Localities'
    | '/Administration/Agencies'
    | '/Administration/Products'
    | '/Administration/Terminals'
    | '/Login'
    | '/Dashboard'
    | '/WorkerManagement/BaseValues/List'
    | '/WorkerManagement/WorkShift/List'
    | '/WorkerManagement/Workers/List'
    | '/WorkerManagement/BaseValues'
    | '/WorkerManagement/WorkShift'
    | '/WorkerManagement/Workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/WorkerAssignments'
    | '/Administration/Admins'
    | '/Administration/Companies'
    | '/Administration/Localities'
    | '/Administration/Agencies'
    | '/Administration/Products'
    | '/Administration/Terminals'
    | '/Login'
    | '/Dashboard'
    | '/WorkerManagement/BaseValues/List'
    | '/WorkerManagement/WorkShift/List'
    | '/WorkerManagement/Workers/List'
    | '/WorkerManagement/BaseValues'
    | '/WorkerManagement/WorkShift'
    | '/WorkerManagement/Workers'
  id:
    | '__root__'
    | '/_private'
    | '/_private/WorkerAssignments'
    | '/_private/Administration/Admins'
    | '/_private/Administration/Companies'
    | '/_private/Administration/Localities'
    | '/_private/Administration/Agencies'
    | '/_private/Administration/Products'
    | '/_private/Administration/Terminals'
    | '/_public/Login/'
    | '/_private/Dashboard/'
    | '/_private/WorkerManagement/BaseValues/List'
    | '/_private/WorkerManagement/WorkShift/List'
    | '/_private/WorkerManagement/Workers/List'
    | '/_private/WorkerManagement/BaseValues/'
    | '/_private/WorkerManagement/WorkShift/'
    | '/_private/WorkerManagement/Workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/WorkerAssignments': {
      id: '/_private/WorkerAssignments'
      path: '/WorkerAssignments'
      fullPath: '/WorkerAssignments'
      preLoaderRoute: typeof PrivateWorkerAssignmentsRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Dashboard/': {
      id: '/_private/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/Login/': {
      id: '/_public/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/Administration/Terminals': {
      id: '/_private/Administration/Terminals'
      path: '/Administration/Terminals'
      fullPath: '/Administration/Terminals'
      preLoaderRoute: typeof PrivateAdministrationTerminalsRouteLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Products': {
      id: '/_private/Administration/Products'
      path: '/Administration/Products'
      fullPath: '/Administration/Products'
      preLoaderRoute: typeof PrivateAdministrationProductsRouteLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Agencies': {
      id: '/_private/Administration/Agencies'
      path: '/Administration/Agencies'
      fullPath: '/Administration/Agencies'
      preLoaderRoute: typeof PrivateAdministrationAgenciesRouteLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Localities': {
      id: '/_private/Administration/Localities'
      path: '/Administration/Localities'
      fullPath: '/Administration/Localities'
      preLoaderRoute: typeof PrivateAdministrationLocalitiesRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Companies': {
      id: '/_private/Administration/Companies'
      path: '/Administration/Companies'
      fullPath: '/Administration/Companies'
      preLoaderRoute: typeof PrivateAdministrationCompaniesRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Admins': {
      id: '/_private/Administration/Admins'
      path: '/Administration/Admins'
      fullPath: '/Administration/Admins'
      preLoaderRoute: typeof PrivateAdministrationAdminsRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/Workers/': {
      id: '/_private/WorkerManagement/Workers/'
      path: '/WorkerManagement/Workers'
      fullPath: '/WorkerManagement/Workers'
      preLoaderRoute: typeof PrivateWorkerManagementWorkersIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/WorkShift/': {
      id: '/_private/WorkerManagement/WorkShift/'
      path: '/WorkerManagement/WorkShift'
      fullPath: '/WorkerManagement/WorkShift'
      preLoaderRoute: typeof PrivateWorkerManagementWorkShiftIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/BaseValues/': {
      id: '/_private/WorkerManagement/BaseValues/'
      path: '/WorkerManagement/BaseValues'
      fullPath: '/WorkerManagement/BaseValues'
      preLoaderRoute: typeof PrivateWorkerManagementBaseValuesIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/Workers/List': {
      id: '/_private/WorkerManagement/Workers/List'
      path: '/WorkerManagement/Workers/List'
      fullPath: '/WorkerManagement/Workers/List'
      preLoaderRoute: typeof PrivateWorkerManagementWorkersListRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/WorkShift/List': {
      id: '/_private/WorkerManagement/WorkShift/List'
      path: '/WorkerManagement/WorkShift/List'
      fullPath: '/WorkerManagement/WorkShift/List'
      preLoaderRoute: typeof PrivateWorkerManagementWorkShiftListRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/WorkerManagement/BaseValues/List': {
      id: '/_private/WorkerManagement/BaseValues/List'
      path: '/WorkerManagement/BaseValues/List'
      fullPath: '/WorkerManagement/BaseValues/List'
      preLoaderRoute: typeof PrivateWorkerManagementBaseValuesListRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateWorkerAssignmentsRouteRoute: typeof PrivateWorkerAssignmentsRouteRoute
  PrivateAdministrationAdminsRouteRoute: typeof PrivateAdministrationAdminsRouteRoute
  PrivateAdministrationCompaniesRouteRoute: typeof PrivateAdministrationCompaniesRouteRoute
  PrivateAdministrationLocalitiesRouteRoute: typeof PrivateAdministrationLocalitiesRouteRoute
  PrivateAdministrationAgenciesRouteLazyRoute: typeof PrivateAdministrationAgenciesRouteLazyRoute
  PrivateAdministrationProductsRouteLazyRoute: typeof PrivateAdministrationProductsRouteLazyRoute
  PrivateAdministrationTerminalsRouteLazyRoute: typeof PrivateAdministrationTerminalsRouteLazyRoute
  PrivateDashboardIndexLazyRoute: typeof PrivateDashboardIndexLazyRoute
  PrivateWorkerManagementBaseValuesListRouteRoute: typeof PrivateWorkerManagementBaseValuesListRouteRoute
  PrivateWorkerManagementWorkShiftListRouteRoute: typeof PrivateWorkerManagementWorkShiftListRouteRoute
  PrivateWorkerManagementWorkersListRouteRoute: typeof PrivateWorkerManagementWorkersListRouteRoute
  PrivateWorkerManagementBaseValuesIndexRoute: typeof PrivateWorkerManagementBaseValuesIndexRoute
  PrivateWorkerManagementWorkShiftIndexRoute: typeof PrivateWorkerManagementWorkShiftIndexRoute
  PrivateWorkerManagementWorkersIndexRoute: typeof PrivateWorkerManagementWorkersIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateWorkerAssignmentsRouteRoute: PrivateWorkerAssignmentsRouteRoute,
  PrivateAdministrationAdminsRouteRoute: PrivateAdministrationAdminsRouteRoute,
  PrivateAdministrationCompaniesRouteRoute:
    PrivateAdministrationCompaniesRouteRoute,
  PrivateAdministrationLocalitiesRouteRoute:
    PrivateAdministrationLocalitiesRouteRoute,
  PrivateAdministrationAgenciesRouteLazyRoute:
    PrivateAdministrationAgenciesRouteLazyRoute,
  PrivateAdministrationProductsRouteLazyRoute:
    PrivateAdministrationProductsRouteLazyRoute,
  PrivateAdministrationTerminalsRouteLazyRoute:
    PrivateAdministrationTerminalsRouteLazyRoute,
  PrivateDashboardIndexLazyRoute: PrivateDashboardIndexLazyRoute,
  PrivateWorkerManagementBaseValuesListRouteRoute:
    PrivateWorkerManagementBaseValuesListRouteRoute,
  PrivateWorkerManagementWorkShiftListRouteRoute:
    PrivateWorkerManagementWorkShiftListRouteRoute,
  PrivateWorkerManagementWorkersListRouteRoute:
    PrivateWorkerManagementWorkersListRouteRoute,
  PrivateWorkerManagementBaseValuesIndexRoute:
    PrivateWorkerManagementBaseValuesIndexRoute,
  PrivateWorkerManagementWorkShiftIndexRoute:
    PrivateWorkerManagementWorkShiftIndexRoute,
  PrivateWorkerManagementWorkersIndexRoute:
    PrivateWorkerManagementWorkersIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
