/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateRouteImport } from './pages/_private'
import { Route as PublicLoginIndexRouteImport } from './pages/_public/Login/index'
import { Route as PrivateAdministrationWorkShiftsRouteRouteImport } from './pages/_private/Administration/WorkShifts/route'
import { Route as PrivateAdministrationLocalitiesRouteRouteImport } from './pages/_private/Administration/Localities/route'
import { Route as PrivateAdministrationCompaniesRouteRouteImport } from './pages/_private/Administration/Companies/route'
import { Route as PrivateAdministrationAdminsRouteRouteImport } from './pages/_private/Administration/Admins/route'

const PrivateDashboardIndexLazyRouteImport = createFileRoute(
  '/_private/Dashboard/',
)()

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/_private.lazy').then((d) => d.Route))
const PrivateDashboardIndexLazyRoute =
  PrivateDashboardIndexLazyRouteImport.update({
    id: '/Dashboard/',
    path: '/Dashboard/',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Dashboard/index.lazy').then((d) => d.Route),
  )
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/Login/',
  path: '/Login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdministrationWorkShiftsRouteRoute =
  PrivateAdministrationWorkShiftsRouteRouteImport.update({
    id: '/Administration/WorkShifts',
    path: '/Administration/WorkShifts',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/WorkShifts/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationLocalitiesRouteRoute =
  PrivateAdministrationLocalitiesRouteRouteImport.update({
    id: '/Administration/Localities',
    path: '/Administration/Localities',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Localities/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationCompaniesRouteRoute =
  PrivateAdministrationCompaniesRouteRouteImport.update({
    id: '/Administration/Companies',
    path: '/Administration/Companies',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Companies/route.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministrationAdminsRouteRoute =
  PrivateAdministrationAdminsRouteRouteImport.update({
    id: '/Administration/Admins',
    path: '/Administration/Admins',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./pages/_private/Administration/Admins/route.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/Administration/WorkShifts': typeof PrivateAdministrationWorkShiftsRouteRoute
  '/Login': typeof PublicLoginIndexRoute
  '/Dashboard': typeof PrivateDashboardIndexLazyRoute
}
export interface FileRoutesByTo {
  '/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/Administration/WorkShifts': typeof PrivateAdministrationWorkShiftsRouteRoute
  '/Login': typeof PublicLoginIndexRoute
  '/Dashboard': typeof PrivateDashboardIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_private/Administration/Admins': typeof PrivateAdministrationAdminsRouteRoute
  '/_private/Administration/Companies': typeof PrivateAdministrationCompaniesRouteRoute
  '/_private/Administration/Localities': typeof PrivateAdministrationLocalitiesRouteRoute
  '/_private/Administration/WorkShifts': typeof PrivateAdministrationWorkShiftsRouteRoute
  '/_public/Login/': typeof PublicLoginIndexRoute
  '/_private/Dashboard/': typeof PrivateDashboardIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/Administration/Admins'
    | '/Administration/Companies'
    | '/Administration/Localities'
    | '/Administration/WorkShifts'
    | '/Login'
    | '/Dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/Administration/Admins'
    | '/Administration/Companies'
    | '/Administration/Localities'
    | '/Administration/WorkShifts'
    | '/Login'
    | '/Dashboard'
  id:
    | '__root__'
    | '/_private'
    | '/_private/Administration/Admins'
    | '/_private/Administration/Companies'
    | '/_private/Administration/Localities'
    | '/_private/Administration/WorkShifts'
    | '/_public/Login/'
    | '/_private/Dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/Dashboard/': {
      id: '/_private/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/Login/': {
      id: '/_public/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/Administration/WorkShifts': {
      id: '/_private/Administration/WorkShifts'
      path: '/Administration/WorkShifts'
      fullPath: '/Administration/WorkShifts'
      preLoaderRoute: typeof PrivateAdministrationWorkShiftsRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Localities': {
      id: '/_private/Administration/Localities'
      path: '/Administration/Localities'
      fullPath: '/Administration/Localities'
      preLoaderRoute: typeof PrivateAdministrationLocalitiesRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Companies': {
      id: '/_private/Administration/Companies'
      path: '/Administration/Companies'
      fullPath: '/Administration/Companies'
      preLoaderRoute: typeof PrivateAdministrationCompaniesRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/Administration/Admins': {
      id: '/_private/Administration/Admins'
      path: '/Administration/Admins'
      fullPath: '/Administration/Admins'
      preLoaderRoute: typeof PrivateAdministrationAdminsRouteRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateAdministrationAdminsRouteRoute: typeof PrivateAdministrationAdminsRouteRoute
  PrivateAdministrationCompaniesRouteRoute: typeof PrivateAdministrationCompaniesRouteRoute
  PrivateAdministrationLocalitiesRouteRoute: typeof PrivateAdministrationLocalitiesRouteRoute
  PrivateAdministrationWorkShiftsRouteRoute: typeof PrivateAdministrationWorkShiftsRouteRoute
  PrivateDashboardIndexLazyRoute: typeof PrivateDashboardIndexLazyRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAdministrationAdminsRouteRoute: PrivateAdministrationAdminsRouteRoute,
  PrivateAdministrationCompaniesRouteRoute:
    PrivateAdministrationCompaniesRouteRoute,
  PrivateAdministrationLocalitiesRouteRoute:
    PrivateAdministrationLocalitiesRouteRoute,
  PrivateAdministrationWorkShiftsRouteRoute:
    PrivateAdministrationWorkShiftsRouteRoute,
  PrivateDashboardIndexLazyRoute: PrivateDashboardIndexLazyRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
